create database DVDdb

use DVDdb;


CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL,
    Mobilenumber NVARCHAR(15) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Nic INT NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);
CREATE TABLE DVDs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Genre NVARCHAR(50) NOT NULL,
    Director NVARCHAR(100) NOT NULL,
    ReleaseDate DATETIME NOT NULL, 
    CopiesAvailable INT NOT NULL
);

CREATE TABLE Rent (
    RentalId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerID UNIQUEIDENTIFIER NOT NULL,
    DVDId UNIQUEIDENTIFIER NOT NULL,
    RentalDate DATETIME NOT NULL,
    Returndate DATETIME NULL,
    Isoverdue BIT NOT NULL,
    Status NVARCHAR(50) NOT NULL
);